server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stock_master?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: jiulong
    password: zjl005
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 122.9.129.71
    port: 6379
    timeout: 1000
    database: 0

ocr:
  service: chaojiyingOcrService
  third:
    aliyun:
      appcode:
    chaojiying:
      user: jiulongting
      pass: zjl005
      softid: 933062

logging:
  file:
    name: /logs/stock-service.log
  logback:
    rollingpolicy:
      max-history: 30
  level:
    root: info
    org.springfromework.web: fatal
    org.springframework.jdbc: fatal
